apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: us-south1-docker.pkg.dev/micro-chiller-458819-r4/oreo-repository/notifications:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: notifications-config
          env:
            - name: SENDER
              valueFrom:
                secretKeyRef:
                  name: notifications-secret
                  key: SENDER
            - name: SENDER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notifications-secret
                  key: SENDER_PASSWORD